module.exports = function( config )
{
	return Object.freeze
	([
		/* 00 */ { land: `gain5`,       pass: null },
		/* 01 */ { land: `chance`,      pass: null },
		/* 02 */ { land: `lose5`,       pass: null },
		/* 03 */ { land: `gain5`,       pass: null },
		/* 04 */ { land: `lose5`,       pass: null },
		/* 05 */ { land: `gain5`,       pass: null },
		/* 06 */ { land: `chance`,      pass: `firstForkOddOrEven` },
		/* 07 */ { land: `gain5`,       pass: null },
		/* 08 */ { land: `minigame`,    pass: null },
		/* 09 */ { land: `gain5`,       pass: null },
		/* 10 */ { land: `chance`,      pass: `toStart` },
		/* 11 */ { land: `chance`,      pass: `secondForkCharactersChoose` },
		/* 12 */ { land: `lose5`,       pass: null },
		/* 13 */ { land: `warpToStart`, pass: null },
		/* 14 */ { land: `gain5`,       pass: null },
		/* 15 */ { land: `warpToStart`, pass: null },
		/* 16 */ { land: `chance`,      pass: null },
		/* 17 */ { land: `warpToStart`, pass: null },
		/* 18 */ { land: `gain5`,       pass: `secondBranchPathsMeet` },
		/* 19 */ { land: `lose5`,       pass: null },
		/* 20 */ { land: `gain5`,       pass: null },
		/* 21 */ { land: `chance`,      pass: null },
		/* 22 */ { land: `goPastCycle`, pass: null },
		/* 23 */ { land: `gain5`,       pass: null },
		/* 24 */ { land: `gain5`,       pass: null },
		/* 25 */ { land: `minigame`,    pass: null },
		/* 26 */ { land: `lose5`,       pass: null },
		/* 27 */ { land: `goPastCycle`, pass: `secondBranchPathStart` },
		/* 28 */ { land: `chance`,      pass: null },
		/* 29 */ { land: `lose5`,       pass: `thirdForkRandom` },
		/* 30 */ { land: `gain5`,       pass: null },
		/* 31 */ { land: `chance`,      pass: null },
		/* 32 */ { land: `lose5`,       pass: null },
		/* 33 */ { land: `minigame`,    pass: null },
		/* 34 */ { land: `gain5`,       pass: null },
		/* 35 */ { land: `lose5`,       pass: null },
		/* 36 */ { land: `gain5`,       pass: null },
		/* 37 */ { land: `chance`,      pass: null },
		/* 38 */ { land: `gain5`,       pass: null },
		/* 39 */ { land: `chance`,      pass: null },
		/* 40 */ { land: `lose5`,       pass: null },
		/* 41 */ { land: `minigame`,    pass: null },
		/* 42 */ { land: `lose5`,       pass: null },
		/* 43 */ { land: `chance`,      pass: null },
		/* 44 */ { land: `lose5`,       pass: `thirdBranchPathsMeet` },
		/* 45 */ { land: `lose5`,       pass: null },
		/* 46 */ { land: `gain5`,       pass: null },
		/* 47 */ { land: `chance`,      pass: null },
		/* 48 */ { land: `lose5`,       pass: null },
		/* 49 */ { land: `lose5`,       pass: null },
		/* 50 */ { land: `chance`,      pass: null },
		/* 51 */ { land: `lose5`,       pass: null },
		/* 52 */ { land: `lose5`,       pass: null },
		/* 53 */ { land: `gain10`,      pass: null },
		/* 54 */ { land: `chance`,      pass: null },
		/* 55 */ { land: `minigame`,    pass: null },
		/* 56 */ { land: `gain10`,      pass: null },
		/* 57 */ { land: `lose10`,      pass: null },
		/* 58 */ { land: `minigame`,    pass: null },
		/* 59 */ { land: `chance`,      pass: null },
		/* 60 */ { land: `lose10`,      pass: null }
	]);
};
